-- This file is generated by pnpm generate:sql. Do not edit manually.
CREATE TABLE IF NOT EXISTS `agent_attachments` (
	`id` text PRIMARY KEY,
	`agent_session_id` text NOT NULL,
	`display_name` text NOT NULL,
	`storage_path` text NOT NULL,
	`media_type` text NOT NULL,
	`byte_length` integer NOT NULL,
	`sha256` text NOT NULL,
	`native_ref` text,
	`transformation` text,
	`created_at` integer NOT NULL,
	CONSTRAINT `fk_agent_attachments_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`agent_session_id`) REFERENCES `agent_sessions`(`id`),
	CONSTRAINT "agent_attachments_length_check" CHECK("byte_length" >= 0)
);

CREATE TABLE IF NOT EXISTS `agent_backend_defaults` (
	`scope_type` text NOT NULL,
	`scope_id` text NOT NULL,
	`backend_type` text NOT NULL,
	`profile_id` text,
	`model_json` text,
	`updated_at` integer NOT NULL,
	CONSTRAINT `agent_backend_defaults_pk` PRIMARY KEY(`scope_type`, `scope_id`),
	CONSTRAINT "agent_backend_defaults_scope_check" CHECK("scope_type" IN ('global', 'channel')),
	CONSTRAINT "agent_backend_type_check" CHECK(backend_type IN ('opencode', 'zcode'))
);

CREATE TABLE IF NOT EXISTS `agent_interactions` (
	`id` text PRIMARY KEY,
	`agent_session_id` text NOT NULL,
	`operation_id` text,
	`connection_generation` text NOT NULL,
	`native_request_id_json` text NOT NULL,
	`kind` text NOT NULL,
	`state` text NOT NULL,
	`safe_request_json` text NOT NULL,
	`controller_thread_id` text NOT NULL,
	`expires_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT `fk_agent_interactions_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`agent_session_id`) REFERENCES `agent_sessions`(`id`),
	CONSTRAINT `fk_agent_interactions_operation_id_agent_operations_id_fk` FOREIGN KEY (`operation_id`) REFERENCES `agent_operations`(`id`),
	CONSTRAINT "agent_interactions_kind_check" CHECK("kind" IN ('permission', 'question', 'plan-approval')),
	CONSTRAINT "agent_interactions_state_check" CHECK("state" IN ('pending', 'answered', 'denied', 'expired', 'stale'))
);

CREATE TABLE IF NOT EXISTS `agent_operations` (
	`id` text PRIMARY KEY,
	`agent_session_id` text NOT NULL,
	`source_type` text NOT NULL,
	`source_id` text NOT NULL,
	`operation_kind` text NOT NULL,
	`controller_thread_id` text NOT NULL,
	`authorized_actor_id` text NOT NULL,
	`payload_json` text NOT NULL,
	`original_hash` text NOT NULL,
	`normalized_hash` text NOT NULL,
	`profile_revision` text,
	`state` text NOT NULL,
	`queue_order` integer,
	`native_command_id` text,
	`native_turn_id` text,
	`connection_generation` text,
	`send_intent_at` integer,
	`accepted_at` integer,
	`terminal_at` integer,
	`outcome_json` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT `fk_agent_operations_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`agent_session_id`) REFERENCES `agent_sessions`(`id`),
	CONSTRAINT "agent_operations_source_check" CHECK("source_type" IN ('discord', 'schedule', 'cli')),
	CONSTRAINT "agent_operations_kind_check" CHECK("operation_kind" IN ('prompt', 'guide', 'answer', 'cancel', 'compact', 'model', 'fork'))
);

CREATE TABLE IF NOT EXISTS `agent_outbox` (
	`id` text PRIMARY KEY,
	`agent_session_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`display_part_id` text NOT NULL,
	`content_revision` integer NOT NULL,
	`payload_json` text NOT NULL,
	`state` text NOT NULL,
	`discord_message_id` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT `fk_agent_outbox_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`agent_session_id`) REFERENCES `agent_sessions`(`id`),
	CONSTRAINT "agent_outbox_state_check" CHECK("state" IN ('pending', 'sending', 'sent', 'delivery-unknown', 'failed'))
);

CREATE TABLE IF NOT EXISTS `agent_schema_versions` (
	`component` text PRIMARY KEY,
	`version` integer NOT NULL,
	CONSTRAINT "agent_schema_version_positive" CHECK("version" > 0)
);

CREATE TABLE IF NOT EXISTS `agent_sessions` (
	`id` text PRIMARY KEY,
	`backend_type` text NOT NULL,
	`native_session_id` text,
	`native_home_identity` text NOT NULL,
	`owner_machine_id` text NOT NULL,
	`project_directory` text NOT NULL,
	`canonical_directory` text NOT NULL,
	`native_workspace_path` text NOT NULL,
	`native_workspace_key` text NOT NULL,
	`profile_id` text,
	`profile_revision` text,
	`runtime_fingerprint` text,
	`model_json` text,
	`controller_thread_id` text,
	`parent_agent_session_id` text,
	`state` text DEFAULT 'creating' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT `fk_agent_sessions_parent_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`parent_agent_session_id`) REFERENCES `agent_sessions`(`id`),
	CONSTRAINT "agent_backend_type_check" CHECK(backend_type IN ('opencode', 'zcode')),
	CONSTRAINT "agent_sessions_zcode_prefix_check" CHECK("backend_type" <> 'zcode' OR substr("id", 1, 3) = 'zc:')
);

CREATE TABLE IF NOT EXISTS `agent_stream_state` (
	`agent_session_id` text NOT NULL,
	`stream_kind` text NOT NULL,
	`log_epoch` text DEFAULT '' NOT NULL,
	`connection_generation` text NOT NULL,
	`sequence` integer,
	`revision` integer,
	`snapshot_json` text,
	`updated_at` integer NOT NULL,
	CONSTRAINT `agent_stream_state_pk` PRIMARY KEY(`agent_session_id`, `stream_kind`),
	CONSTRAINT `fk_agent_stream_state_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`agent_session_id`) REFERENCES `agent_sessions`(`id`),
	CONSTRAINT "agent_stream_state_kind_check" CHECK("stream_kind" IN ('legacy', 'v4'))
);

CREATE TABLE IF NOT EXISTS `agent_thread_intents` (
	`thread_id` text PRIMARY KEY,
	`backend_type` text NOT NULL,
	`profile_id` text,
	`profile_revision` text,
	`owner_machine_id` text NOT NULL,
	`state` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "agent_backend_type_check" CHECK(backend_type IN ('opencode', 'zcode')),
	CONSTRAINT "agent_thread_intents_state_check" CHECK("state" IN ('workspace-pending', 'ready-to-bind', 'bound', 'failed'))
);

CREATE TABLE IF NOT EXISTS `agent_workspace_leases` (
	`resource` text PRIMARY KEY,
	`agent_session_id` text NOT NULL,
	`owner_nonce` text NOT NULL,
	`acquired_at` integer NOT NULL,
	CONSTRAINT `fk_agent_workspace_leases_agent_session_id_agent_sessions_id_fk` FOREIGN KEY (`agent_session_id`) REFERENCES `agent_sessions`(`id`)
);

CREATE TABLE IF NOT EXISTS `bot_api_keys` (
	`app_id` text PRIMARY KEY,
	`gemini_api_key` text,
	`openai_api_key` text,
	`xai_api_key` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_bot_api_keys_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `bot_tokens` (
	`app_id` text PRIMARY KEY,
	`token` text NOT NULL,
	`bot_mode` text DEFAULT 'self_hosted' NOT NULL,
	`client_id` text,
	`client_secret` text,
	`proxy_url` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`last_used_at` datetime
);

CREATE TABLE IF NOT EXISTS `channel_agents` (
	`channel_id` text PRIMARY KEY,
	`agent_name` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_agents_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_directories` (
	`channel_id` text PRIMARY KEY,
	`directory` text NOT NULL,
	`channel_type` text NOT NULL,
	`guild_id` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `channel_mention_mode` (
	`channel_id` text PRIMARY KEY,
	`enabled` integer DEFAULT 0 NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_mention_mode_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_models` (
	`channel_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_models_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_verbosity` (
	`channel_id` text PRIMARY KEY,
	`verbosity` text DEFAULT 'tools_and_text' NOT NULL,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_verbosity_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_worktrees` (
	`channel_id` text PRIMARY KEY,
	`enabled` integer DEFAULT 0 NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_worktrees_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `forum_sync_configs` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`app_id` text NOT NULL,
	`forum_channel_id` text NOT NULL,
	`output_dir` text NOT NULL,
	`direction` text DEFAULT 'bidirectional' NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_forum_sync_configs_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `global_models` (
	`app_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_global_models_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `ipc_requests` (
	`id` text PRIMARY KEY,
	`type` text NOT NULL,
	`session_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`payload` text NOT NULL,
	`response` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT `fk_ipc_requests_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `part_messages` (
	`part_id` text PRIMARY KEY,
	`message_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_part_messages_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `scheduled_task_runs` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`scheduled_task_id` integer NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`thread_id` text,
	`session_id` text,
	`project_directory` text,
	`started_at` datetime NOT NULL,
	`completed_at` datetime,
	`error` text,
	CONSTRAINT `fk_scheduled_task_runs_scheduled_task_id_scheduled_tasks_id_fk` FOREIGN KEY (`scheduled_task_id`) REFERENCES `scheduled_tasks`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `scheduled_tasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`status` text DEFAULT 'planned' NOT NULL,
	`schedule_kind` text NOT NULL,
	`run_at` datetime,
	`cron_expr` text,
	`timezone` text,
	`next_run_at` datetime NOT NULL,
	`running_started_at` datetime,
	`last_run_at` datetime,
	`last_error` text,
	`attempts` integer DEFAULT 0 NOT NULL,
	`payload_json` text NOT NULL,
	`prompt_preview` text NOT NULL,
	`channel_id` text,
	`thread_id` text,
	`session_id` text,
	`project_directory` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_scheduled_tasks_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT `fk_scheduled_tasks_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `session_agents` (
	`session_id` text PRIMARY KEY,
	`agent_name` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `session_events` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`session_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`timestamp` integer NOT NULL,
	`event_index` integer NOT NULL,
	`event_json` text NOT NULL,
	CONSTRAINT `fk_session_events_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `session_models` (
	`session_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `session_sleeps` (
	`session_id` text PRIMARY KEY,
	`wake_at` datetime NOT NULL,
	`reason` text,
	`status` text DEFAULT 'planned' NOT NULL,
	`delivery_id` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`last_attempt_at` datetime,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `session_start_sources` (
	`session_id` text PRIMARY KEY,
	`schedule_kind` text NOT NULL,
	`scheduled_task_id` integer,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_session_start_sources_scheduled_task_id_scheduled_tasks_id_fk` FOREIGN KEY (`scheduled_task_id`) REFERENCES `scheduled_tasks`(`id`) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `thread_sessions` (
	`thread_id` text PRIMARY KEY,
	`session_id` text NOT NULL,
	`source` text DEFAULT 'kimaki' NOT NULL,
	`last_synced_name` text,
	`parent_session_id` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `thread_workspaces` (
	`thread_id` text PRIMARY KEY,
	`workspace_id` text,
	`workspace_type` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`error_message` text,
	`project_directory` text NOT NULL,
	`workspace_directory` text,
	`workspace_name` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_thread_workspaces_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `thread_worktrees` (
	`thread_id` text PRIMARY KEY,
	`worktree_name` text NOT NULL,
	`worktree_directory` text,
	`project_directory` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`error_message` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_thread_worktrees_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS `agent_interactions_pending_id` ON `agent_interactions` (`agent_session_id`,`connection_generation`,`native_request_id_json`) WHERE "agent_interactions"."state" = 'pending';
CREATE UNIQUE INDEX IF NOT EXISTS `agent_operations_source_unique` ON `agent_operations` (`agent_session_id`,`source_type`,`source_id`,`operation_kind`);
CREATE INDEX IF NOT EXISTS `agent_operations_queue` ON `agent_operations` (`agent_session_id`,`state`,`queue_order`);
CREATE UNIQUE INDEX IF NOT EXISTS `agent_outbox_revision_unique` ON `agent_outbox` (`thread_id`,`display_part_id`,`content_revision`);
CREATE UNIQUE INDEX IF NOT EXISTS `agent_sessions_native_identity` ON `agent_sessions` (`backend_type`,`owner_machine_id`,`native_home_identity`,`native_session_id`) WHERE native_session_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS `forum_sync_configs_app_id_forum_channel_id_key` ON `forum_sync_configs` (`app_id`,`forum_channel_id`);
CREATE INDEX IF NOT EXISTS `ipc_requests_status_created_at_idx` ON `ipc_requests` (`status`,`created_at`);
CREATE INDEX IF NOT EXISTS `scheduled_task_runs_task_status_idx` ON `scheduled_task_runs` (`scheduled_task_id`,`status`);
CREATE INDEX IF NOT EXISTS `scheduled_task_runs_session_status_idx` ON `scheduled_task_runs` (`session_id`,`status`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_status_next_run_at_idx` ON `scheduled_tasks` (`status`,`next_run_at`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_channel_id_status_idx` ON `scheduled_tasks` (`channel_id`,`status`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_thread_id_status_idx` ON `scheduled_tasks` (`thread_id`,`status`);
CREATE INDEX IF NOT EXISTS `session_events_session_id_timestamp_event_index_id_idx` ON `session_events` (`session_id`,`timestamp`,`event_index`,`id`);
CREATE INDEX IF NOT EXISTS `session_events_thread_id_timestamp_event_index_id_idx` ON `session_events` (`thread_id`,`timestamp`,`event_index`,`id`);
CREATE INDEX IF NOT EXISTS `session_sleeps_status_wake_at_idx` ON `session_sleeps` (`status`,`wake_at`);
CREATE INDEX IF NOT EXISTS `session_start_sources_scheduled_task_id_idx` ON `session_start_sources` (`scheduled_task_id`);
